### PR TITLE
Plugin config fix

### PR DESCRIPTION
**Pull request by scabala**
When using custom plugins, user-modified configuration is not saved in plugin's json file. It is caused by fact that instance of `PluginConfigurationStore` in plugin object and in each one of preference items are different objects. Therefore, when changing configuration in dialog and saving configuration from plugin, only default configuration is saved.

This PR fixes it by reusing plugins in preferences dialog instead of re-instantiating them each time dialog is executed.

his might be very ugly solution and I open for suggestions

### CODE REVIEW

**Comment by otsaloma** [comment]
Thanks for noticing, I now see the problem.

This solution doesn't work however, `Window._plugins` is only a list of active plugins. All plugins are needed for the preferences dialog. That's also why `conf` is a class attribute, because it needs to be available without instantiating the plugin.

A simpler fix would be to memoize `util.load_plugin_module`, but that needs some kind of handling not to break the `:reload-plugins` builtin command. If you want to look into it, go ahead, if you can't make sense of it, I can take a look too. The plugin config system turned out unfortunately complicated specifically because of having to deal with both active and inactive plugins and also in the code it's not always clear whether `plugin` is the name, class or instance or why it is what it is.

**Comment by scabala** [comment]
Ah, I should have know it would not be *that* easy. I'll try work with that a bit again.

**Comment by otsaloma** [comment]
I want to move on with this, I'm working on a fix now.

**Comment by otsaloma** [comment]
FYI

* https://github.com/otsaloma/catapult/commit/912b548db7c704e49415e78553dce3b1384696d2
* https://github.com/otsaloma/catapult/commit/4e02acac7feed62a9079cba973ffbe9eca577cbc

Should be fixed, though not tested thoroughly yet.

**Pull request closed without merging**
